from __future__ import annotations

import hashlib
import hmac
import json
import secrets
from dataclasses import dataclass
from typing import Any

PBKDF2_ALGORITHM = "sha256"
PBKDF2_ITERATIONS = 260_000
PBKDF2_PREFIX = "pbkdf2_sha256"


@dataclass(frozen=True)
class AppUser:
    username: str
    display_name: str
    role: str = "user"
    active: bool = True
    password: str = ""
    password_hash: str = ""


def make_password_hash(password: str, *, iterations: int = PBKDF2_ITERATIONS) -> str:
    """Create a PBKDF2-SHA256 password hash suitable for PATENT_USERS_JSON."""
    if not isinstance(password, str) or not password:
        raise ValueError("Parola boş olamaz.")
    salt = secrets.token_hex(16)
    digest = hashlib.pbkdf2_hmac(
        PBKDF2_ALGORITHM,
        password.encode("utf-8"),
        salt.encode("ascii"),
        iterations,
    ).hex()
    return f"{PBKDF2_PREFIX}${iterations}${salt}${digest}"


def verify_password(password: str, stored_hash: str) -> bool:
    """Verify PBKDF2-SHA256 hashes generated by make_password_hash."""
    try:
        prefix, iterations_raw, salt, expected = str(stored_hash).split("$", 3)
        if prefix != PBKDF2_PREFIX:
            return False
        iterations = int(iterations_raw)
        if iterations < 100_000:
            return False
        actual = hashlib.pbkdf2_hmac(
            PBKDF2_ALGORITHM,
            str(password).encode("utf-8"),
            salt.encode("ascii"),
            iterations,
        ).hex()
        return hmac.compare_digest(actual, expected)
    except Exception:
        return False


def _normalize_user(username: str, raw: Any) -> AppUser:
    username = str(username or "").strip()
    if not username:
        raise ValueError("Kullanıcı adı boş olamaz.")

    if isinstance(raw, str):
        return AppUser(
            username=username,
            display_name=username,
            role="user",
            active=True,
            password=raw,
        )

    if not isinstance(raw, dict):
        raise ValueError(f"{username!r} kullanıcısının yapılandırması geçersiz.")

    display_name = str(raw.get("display_name") or raw.get("name") or username).strip() or username
    role = str(raw.get("role") or "user").strip().lower() or "user"
    active = bool(raw.get("active", True))
    password = str(raw.get("password") or "")
    password_hash = str(raw.get("password_hash") or "")
    if not password and not password_hash:
        raise ValueError(f"{username!r} kullanıcısı için password veya password_hash tanımlayın.")
    return AppUser(
        username=username,
        display_name=display_name,
        role=role,
        active=active,
        password=password,
        password_hash=password_hash,
    )


def load_users(raw_json: str) -> dict[str, AppUser]:
    """Parse PATENT_USERS_JSON into username -> AppUser mapping.

    Supported forms:
      {"samet": {"password": "...", "display_name": "Samet", "role": "admin"}}
      [{"username": "samet", "password_hash": "...", ...}]
    """
    raw_json = str(raw_json or "").strip()
    if not raw_json:
        return {}
    try:
        payload = json.loads(raw_json)
    except json.JSONDecodeError as exc:
        raise ValueError("PATENT_USERS_JSON geçerli JSON değil.") from exc

    users: dict[str, AppUser] = {}
    if isinstance(payload, dict):
        for username, raw in payload.items():
            user = _normalize_user(str(username), raw)
            users[user.username] = user
    elif isinstance(payload, list):
        for item in payload:
            if not isinstance(item, dict):
                raise ValueError("PATENT_USERS_JSON liste biçiminde ise her kayıt nesne olmalıdır.")
            username = str(item.get("username") or "").strip()
            user = _normalize_user(username, item)
            users[user.username] = user
    else:
        raise ValueError("PATENT_USERS_JSON JSON nesnesi veya listesi olmalıdır.")

    return users


def authenticate(users: dict[str, AppUser], username: str, password: str) -> AppUser | None:
    """Return the active user on successful authentication, otherwise None."""
    username = str(username or "").strip()
    user = users.get(username)
    if user is None or not user.active:
        # Do a small comparable operation even for an unknown user to avoid a trivial fast path.
        hmac.compare_digest(str(password or ""), "not-a-real-password")
        return None

    if user.password_hash:
        ok = verify_password(str(password or ""), user.password_hash)
    else:
        ok = hmac.compare_digest(str(password or ""), user.password)
    return user if ok else None
